version: "2"
services:
  nginx:
    ports:
      - "80:80"
    build: .
    volumes:
      - /home/mishgunn/una/prod/shared:/var/www/prod/univ-nantes-aviron/shared


  mysql:
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Unanantes1.0
    volumes:
      - /home/mishgunn/una/db:/var/lib/mysql
    image:
      mysql:8.0.2
